// <auto-generated />
using Jason5Lee.PropertyCharge.Boundary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Jason5Lee.PropertyCharge.Migrations
{
    [DbContext(typeof(PropertyChargeDbContext))]
    partial class PropertyChargeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Jason5Lee.PropertyCharge.Models.Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PersonaleId")
                        .HasColumnType("numeric(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaleId");

                    b.ToTable("Charges");
                });

            modelBuilder.Entity("Jason5Lee.PropertyCharge.Models.Personale", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("char(32)");

                    b.HasKey("Id");

                    b.ToTable("Personales");
                });

            modelBuilder.Entity("Jason5Lee.PropertyCharge.Models.Charge", b =>
                {
                    b.HasOne("Jason5Lee.PropertyCharge.Models.Personale", "Personale")
                        .WithMany()
                        .HasForeignKey("PersonaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personale");
                });
#pragma warning restore 612, 618
        }
    }
}
